apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: module-cleanup
  labels:
    app: module-cleanup
  namespace: folio-default
spec:
  schedule: "41 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: controller-service-account
          containers:
            - name: module-cleanup
              image: folioci/folioci-cleanup:latest
              envFrom:
              - secretRef:
                  name: tenant-cleanup-env
              args: 
                - "-o"
                - "https://okapi-default.ci.folio.org"
                - "-r"
                - "3"
                - "-s"
                - "2"
                - "-u"
                - "username"
                - "$(CLEANUP_OKAPI_USER)"
                - "-p"
                - "$(CLEANUP_OKAPI_PASSWORD)"

