apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup-test
  labels:
    app: cleanup-test
  namespace: folio-default
spec:
  schedule: "41 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: controller-service-account
          containers:
            - name: cleanup-test
              image: folioci/folioci-cleanup:0.1.1
              args: 
                - "-o"
                - "https://okapi-default.ci.folio.org"
                - "-r"
                - "3"
                - "-s"
                - "2"
                - "-u"
                - "username"
                - "-p"
                - "password"

